### ISSUE TITLE
Memory usage 0.6.2

### ISSUE THREAD

**Issue by jamesahendry** [QuantumEntangledAndy/neolink#157] opened 2023-09-27 01:05 UTC
Can I get you to check the mem growth in the scenario where you access both the SubSteam and Mainsteam? I use this in Frigate BTW. I have some of my cams that detect on the Mainsteam only due to the field of view and I've cut the cam up into different zones within Frigate. Other cams I use substeam to detect and mainstream to record. I am seeing vastly different memory growth when I am accessing both the sub and mainstreams compared to the mainstream only (which is 4K). The 4K only memory steam is very static - very consistent on 0.6.2. The sub/main combination is consistently growing and I run reboot on the Bullseye container when it gets close to 1GB. 1 cam per container. Here's the difference yesterday. I have 3 cams running mainsteam only and 3 cams running sub/main so the consistency is absolute based on the scenarios described. There's also an auto reboot at circa 4AM due to the memory issues. I could isolcate this by spinning up a new LXC and splitting the sub/main and test if you want? In this scenario the driveway cam is mainsteam only - courtyard sub/main.  As you can see the Mainstream only is static at about 240mb of memory, the cams that use the sub and mainsteam are consistantly growing.

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/bf6fad37-3124-4cc8-9bc0-68c842aea467)
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/8152cbfb-1ca1-4b5f-a25a-285521d6e7ea)

**Comment by QuantumEntangledAndy** [comment] 2023-09-27 01:17
The bigest memory issue left after 0.6.2 is in gstreamer. Gstreamer has its own internal set of buffers and those increase the more streams you have. This build [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6319895176/job/17162022707) (if I can get windows to build) contains some more strict limits on the gstreamer buffer that should fix this

**Comment by QuantumEntangledAndy** [comment] 2023-09-27 02:10
Well it is built now so please try it. (Just needed a retry since windows will randomly fail to download the dependencies some time)

**Comment by jamesahendry** [comment] 2023-09-27 02:16
All good - I'll sort this out when I get home later tonight.  I'm in Melbourne / AU.

**Comment by jamesahendry** [comment] 2023-09-27 12:43
Just got home and put the version linked in this thread on and memory usage is hard to comment on, however I'm not getting a clear feed.  This is replicated in VLC.   If you look at things like the time that should consistently count up second by second, it seems to skip frames and then produce "snow in the picture"

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/73198467-c7aa-4316-9f43-a6eb3447600c)
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/fcc285dd-5c06-4e7e-96b4-eb93d38dbec6)

**Comment by QuantumEntangledAndy** [comment] 2023-09-27 13:14
Hard to say for sure without me looking deeper into it. It may have something to do with the memory limits on the buffers filling and it dropping frames. 

Can you estimate the bitrate you are getting I'll try to work out what size buffers we need for about 15s of stream.

**Comment by QuantumEntangledAndy** [comment] 2023-09-27 13:15
P.s. my time zone is +7 so not too much difference.

**Comment by jamesahendry** [comment] 2023-09-27 13:38
If I throw the stream into VLC - this is what I get for a 4K stream but it fluctuates between 2000 kb/s and 6000 and on a substeam between 500 kb/s and 700 kb/s....I would imagine this would change in daylight

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/269f6ba7-85a2-4e3b-93e1-e7cfbe22927e)

**Comment by jamesahendry** [comment] 2023-09-27 22:17
Interestingly - Here's two cameras running Sub and Main.  Backgrass is on 0.6.2.  Courtyard is on the last version published from https://github.com/thirtythreeforty/neolink.

I flipped over Courtyard last night before I went to bed and they both rebooot just before 5 AM.  Courtyard which is on https://github.com/thirtythreeforty/neolink seems to have stablised

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/739c24a3-8963-4bfa-9de2-31e0d63a9a80)
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/c42a1c1c-2c11-4b20-a181-e322ca812f8d)

**Comment by QuantumEntangledAndy** [comment] 2023-09-27 22:24
The 4k seems really large. 6000kbs is 6mbs so 15s of that is 90mb per client the stream is currently set to 10mb per client so gstreamer can currently buffer about 1.6s of this.

Could you run with debug log on (the env variable `RUST_LOG="neolink=debug"`) it might show us how often the stream is being kicked.

I expect some visuals aftifactes whenever a stream is restarted because there's no good way to join the end of the old stream with the beginning of the new without a re-encode (which we want to avoid because of the computational expense)

**Comment by jamesahendry** [comment] 2023-09-28 00:26
No worries - it's the 4K only stream that is fine though.  On 0.6.2 It's not growing in memory.  It's only when I have the sub+main that I have the constant memory leak.  I'll run the log and see what I can produce for you.

**Comment by QuantumEntangledAndy** [comment] 2023-09-28 02:45
This is what I get with both substream and mainstream over 15min

<img width="1276" alt="Screenshot 2023-09-28 at 09 43 24" src="https://github.com/QuantumEntangledAndy/neolink/assets/13386481/be0534d3-697c-4207-a02b-fae7049f0c7b">

Seems to be fairly constant

**Comment by MicheleCardamone** [comment] 2023-09-28 04:57
> This is what I get with both substream and mainstream over 15min
> 
> 
> 
> <img width="1276" alt="Screenshot 2023-09-28 at 09 43 24" src="https://github.com/QuantumEntangledAndy/neolink/assets/13386481/be0534d3-697c-4207-a02b-fae7049f0c7b">
> 
> 
> 
> Seems to be fairly constant
> 
> 

Hi! @QuantumEntangledAndy 
for your memory investigation, perhaps it would be useful to know that after many hours the dreaded "reaching limit of channel" error reappeared also on 0.6.2 master. Look at the related topic, I published some information yesterday

**Comment by QuantumEntangledAndy** [comment] 2023-09-28 05:09
@MicheleCardamone could you try to replicate on the build posted here? I've already added something to try to mitigate that in the release for after 0.6.2

**Comment by QuantumEntangledAndy** [comment] 2023-09-28 05:11
My memory profiler though is limited to about 20mins before it has trouble. It's not just reading the ram useage but every allocation and tracking memory destruction down to the actual code level so there's a limit to how long I can profile for. 

Might be able to profile for longer on a dedicated Linux box and valgrind though.

**Comment by MicheleCardamone** [comment] 2023-09-28 13:58
> My memory profiler though is limited to about 20mins before it has trouble. It's not just reading the ram useage but every allocation and tracking memory destruction down to the actual code level so there's a limit to how long I can profile for. 
> 
> Might be able to profile for longer on a dedicated Linux box and valgrind though. 

Hi! @QuantumEntangledAndy 
I tested the build you put here. It seems to give problems on the substream (0 fps as you see in the photo). Currently 0.6.2 master seems to be the best version, except that after many hours of use the reaching limit of channel error returns and saturates the RAM more and more.
even 0.6.2 master still seems to always give the "stream not ready" message at startup 
![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/259012c4-8703-44a8-8512-ad111be62a91)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/f94d54aa-d6d5-43c1-9303-f87193d22e67)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/2f705ab9-1d04-4e10-83ec-fe4920d8a618)

**Comment by QuantumEntangledAndy** [comment] 2023-09-28 14:21
You'll Get stream not ready if you connect before the stream available at message. If you get stream not ready fps will be zero (since this temp stops after so many frames). If your bi software dosent reconnect in this situation set `use_splash` to false in the config

**Comment by jamesahendry** [comment] 2023-09-28 22:48
@MicheleCardamone what are you using there to troubleshoot the bitrates?

**Comment by QuantumEntangledAndy** [comment] 2023-09-29 06:54
I'm wondering if frigate/bi is opening multiple connections (and not closing them) 

If you have time could you run [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6335115426) with debug log on and report on the numbers for the message `Number of rtsp clients:`

**Comment by jamesahendry** [comment] 2023-09-29 06:57
Will do!  Long weekend here so might be early next week.  Thanks so much for your efforts

Get Outlook for iOS<https://aka.ms/o0ukef>

James Hendry
General Manager  Commercial
D 03 8696 9304M 0400 660 006
E ***@***.***
CONFIDENTIALITY NOTICE:  The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.
________________________________

**Comment by MicheleCardamone** [comment] 2023-09-29 07:22
> what are you using there to troubleshoot the bitrates?

I didn't read the problem you have. What do you mean by bitrate problem?

**Comment by MicheleCardamone** [comment] 2023-09-29 12:37
@QuantumEntangledAndy 

Hi!
Tried with use_splash=false and it seems to give the same problems. Unusable unfortunately 🙁

**Comment by MicheleCardamone** [comment] 2023-10-01 07:02
Hi! @QuantumEntangledAndy 
Any news about memory? Thx
Mc

**Comment by QuantumEntangledAndy** [comment] 2023-10-01 07:10
Do you have a debug log for me? From the last build posted above. I want to see if frigate/Bi is creating multiple streams

**Comment by jamesahendry** [comment] 2023-10-01 09:05
I am just about to load the build in the post again and send the debug logs

**Comment by jamesahendry** [comment] 2023-10-01 09:29
Hi @QuantumEntangledAndy - I've loaded the build that you've referenced in this post.  This is the build that gives me a lot of broken frames.  I don't really mind because I've got multiple cams.  Anyway - just confirming - this should be the syntax in the .toml?  Should I see a debug file into neolink folder?
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/07513eda-899f-468b-a65d-5066f419c9c1)

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/8a47c627-2819-4dcf-bbd4-7fb1f71841bc)

**Comment by MicheleCardamone** [comment] 2023-10-01 14:36
> Do you have a debug log for me? From the last build posted above. I want to see if frigate/Bi is creating multiple streams

I don't know how to enable debugging on windows. can you help me?

**Comment by QuantumEntangledAndy** [comment] 2023-10-01 23:17
Are you use CMD or powershell or docker. You just need to set an environmental variable called `RUST_LOG` to `"neolink=debug`

**Comment by jamesahendry** [comment] 2023-10-01 23:28
No docker just straight command line in Debian12 which is an LXC container on Proxmox.  Clearly this isn't meant to go in the .toml - sorry my ignorance - I'll sort it out when I get home tonight.  Good news is that since I changed to the build linked in this discussion - memory very stable.  You can see where I've changed it just before 8pm last night.  I do get a lot of snow and interference on the stream

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/119c27ab-54b6-4ebf-8186-3d096bf5021c)

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/cb5adb0d-0e46-490c-9b01-29887434bde9)

**Comment by QuantumEntangledAndy** [comment] 2023-10-01 23:29
@jamesahendry RUST_LOG is not a config option but an environmental variable. You'll need to set it in the options of your proxmox server.

**Comment by jamesahendry** [comment] 2023-10-02 08:58
Hi @QuantumEntangledAndy - it's run as supervisord on each Debian LXC.   I've now edited the supervisor .conf file as follows and the LCX takes your export command.  Where would it drop the log within the Debian OS?


![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/35281112-1e67-474f-8eea-9bf45104ff6b)

**Comment by QuantumEntangledAndy** [comment] 2023-10-02 09:19
That dosent look like or seem to be working like a normal shell. I think you should Google how to set an environmental variable on a proxmax

**Comment by QuantumEntangledAndy** [comment] 2023-10-02 09:20
Looks more like your using nano to edit a config file in toml format.

**Comment by MicheleCardamone** [comment] 2023-10-02 15:33
Update: Googling I managed to enable (correctly I think) debugging with "set RUST_LOG=neolink=debug". I don't know what to send you because the build sent here generates lots of error messages. Trying it instead with 0.6.2 master it doesn't seem to give errors.
![Screenshot 2023-10-02 173335](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/c09267ae-85d3-4877-885f-6c2fee13b1e4)
![Screenshot 2023-10-02 173252](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/37085ca5-e938-4a91-a50b-a82186fe1c37)

**Comment by jamesahendry** [comment] 2023-10-02 22:47
@MicheleCardamone - are you running both a subStream and mainStream?  I'm at the point where I'm just running a single 4K stream and the memory usage is awesome on 0.6.2.  It's as soon as I introduce both streams that Neolink leaks memory. @QuantumEntangledAndy - I'll get the "set RUST_LOG=neolink=debug" sorted for you shortly and I'll install the version in this thread

6 - cams all on mainSteam only - memory usage is stable as can be.  In fact on some of these charts you can see where I moved them to mainStream only at midnight last night.  I haven't pasted all the charts as they all say the same thing.  Frigate logs are clear.  

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/03f14388-dde7-400c-8702-771db78ea9ee)
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/554d49ff-8ede-4971-ab68-10dffb47a975)
![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/0126633e-0347-47a2-a3cb-22222653d7dc)

**Comment by QuantumEntangledAndy** [comment] 2023-10-02 23:32
After your neolink command can you pipe the result into a file and send that.

It should be in CMD

set RUST_LOG="neolink=debug"
neolink rtsp --config=file.toml > neolink.log

You won't see a log coz it will be sent into the file but please try your connections then send me the log. (Only about 10mins is fine)

**Comment by QuantumEntangledAndy** [comment] 2023-10-03 04:17
I think I have identified the source of the artifacts. It was the change to send messages on via a task so as to reduce blocking, but it causes out of order frames.

**Comment by QuantumEntangledAndy** [comment] 2023-10-03 05:03
Ok so hopefully this [build is good](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6388831582) if we can't find any major issues with it. I think it would be good to release since it contains quite a few bug fixes

**Comment by jamesahendry** [comment] 2023-10-03 06:24
> Ok so hopefully this [build is good](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6388831582) if we can't find any major issues with it. I think it would be good to release since it contains quite a few bug fixes

I will load onto a cam tonight and test.

**Comment by MicheleCardamone** [comment] 2023-10-03 10:56
> Ok so hopefully this [build is good](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6388831582) if we can't find any major issues with it. I think it would be good to release since it contains quite a few bug fixes

@QuantumEntangledAndy 
Started this build. The problem of the SUBstream not working seems to have been corrected but unfortunately another one has reappeared: an unstable stream. The fps of both the main and the sub fluctuate a lot, making the image less fluid, which however on 0.6.2 master seems to be resolved.

**Comment by jamesahendry** [comment] 2023-10-03 11:11
I am just going to load now and report back

**Comment by MicheleCardamone** [comment] 2023-10-03 11:17
@QuantumEntangledAndy If it helps, this is the log (even if I open it I can't read anything written) of the version you put here that gave me neolink in about 10 minutes of operation.
[neolink.log](https://github.com/QuantumEntangledAndy/neolink/files/12791922/neolink.log)

**Comment by QuantumEntangledAndy** [comment] 2023-10-03 11:23
You cannot read it because the file is zero bytes.. I forgot that logs are written to stderr to std out so the command to write stderr and stdout to file is as follows

```cmd
set RUST_LOG="neolink=debug"
neolink rtsp --config=file.toml > neolink.log 2>&1
```

The `2>&1` means put stderr into stdout and the `> neolink.log` means put stdout into `neolink.log`

**Comment by QuantumEntangledAndy** [comment] 2023-10-03 11:30
> The fps of both the main and the sub fluctuate a lot, making the image less fluid, which however on 0.6.2 master

I just went through the complete diff of all changes from 0.6.2. 75% of it is just bug fixes and the new push notficiation stuff. There appears to be only three significatnt changes to the stream data.

1. The buffer size way changed and is not calculated from the reported bitrate
2. Frames are not put into the gstreamer pipeline until their frametime matches the runtime
3. We timeout and reconnect a stream after 15s instead of 4

I can make a build that disables these things but are you willing to test

**Comment by jamesahendry** [comment] 2023-10-03 11:34
> > The fps of both the main and the sub fluctuate a lot, making the image less fluid, which however on 0.6.2 master
> 
> I just went through the complete diff of all changes from 0.6.2. 75% of it is just bug fixes and the new push notficiation stuff. There appears to be only three significatnt changes to the stream data.
> 
> 1. The buffer size way changed and is not calculated from the reported bitrate
> 2. Frames are not put into the gstreamer pipeline until their frametime matches the runtime
> 3. We timeout and reconnect a stream after 15s instead of 4
> 
> I can make a build that disables these things but are you willing to test

Of Course - I've got 6 cams on Neolink

**Comment by MicheleCardamone** [comment] 2023-10-03 12:03
> 



> > The fps of both the main and the sub fluctuate a lot, making the image less fluid, which however on 0.6.2 master
> 
> I just went through the complete diff of all changes from 0.6.2. 75% of it is just bug fixes and the new push notficiation stuff. There appears to be only three significatnt changes to the stream data.
> 
> 1. The buffer size way changed and is not calculated from the reported bitrate
> 2. Frames are not put into the gstreamer pipeline until their frametime matches the runtime
> 3. We timeout and reconnect a stream after 15s instead of 4
> 
> I can make a build that disables these things but are you willing to test

sure, no problem carrying out tests. This is the log

[neolink.log](https://github.com/QuantumEntangledAndy/neolink/files/12792206/neolink.log)

**Comment by MicheleCardamone** [comment] 2023-10-03 12:04
> I'm really stuggling with this latest build in Frigate - moving between stream not ready and not receiving any frames. Can't even get it going in VLC - it just sits there. Wound back to 0.6.2 and it came straight back up in Frigate and VLC
> 
> ![image](https://user-images.githubusercontent.com/67103059/272251066-2ad25a36-652f-453a-9dbe-3aacbe7c249e.png) ![image](https://user-images.githubusercontent.com/67103059/272251282-67bd50c0-7bc9-49c6-8aea-b979125ca37c.png) ![image](https://user-images.githubusercontent.com/67103059/272251382-db79cdc3-53c3-4aad-b69d-769d0d7b4d97.png)

I don't want to be wrong, I also had this similar problem in BI. Try putting use_splash = false

**Comment by jamesahendry** [comment] 2023-10-03 12:07
> use_splash = false

I also reviewed my Frigate config and I was running the subStream detect in 3480 x 2160.  It shouldn't have prevented the stream loading in VLCthrough.  I'll try that

**Comment by QuantumEntangledAndy** [comment] 2023-10-05 04:23
When it finishes building please try out [this one](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6414580353)

**Comment by QuantumEntangledAndy** [comment] 2023-10-05 04:24
VLC is often difficult in the way it expects the timestamps to be presented. I swapped out some of the code for the previous iteration and also adjusted the time stamp calculations so hopefully it will work better now

**Comment by QuantumEntangledAndy** [comment] 2023-10-05 04:25
With frigate though there seems to be something with frigate opening multiple client connctions. Not sure if this is by design on frigates end, but might be putting a bit of strain on neolink

**Comment by jamesahendry** [comment] 2023-10-05 08:57
> When it finishes building please try out [this one](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6414580353)

I can't even open the rtsp steam on this build.  Both Frigate and VLC.  Is there anything different about the steam name or anything?

Have tried 
rtsp://10.0.45.25:8554/courtyard
rtsp://10.0.45.25:8554/mainSteam

The service is up and I can telnet to it on 8554.  Have wound back to 0.6.2 no issues

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/9fa88ad8-1087-4755-af06-aac4355ce3a7)

**Comment by QuantumEntangledAndy** [comment] 2023-10-05 09:02
Nope if I change anything major like that I'd let you know. A log file please, because I picture of the config tells me very little.

Also please be aware that:

```toml
bind = "0.0.0.0"
stream = "both" # Does nothing here remove it

[[cameras]]
name = "courtyard"
username = "admin"
password = ""
address = "10.0.45.87:9000"
stream = "mainStream" # correct location
user_splash = false
```

The log will tell you the possible paths when it says avaliable at

**Comment by jamesahendry** [comment] 2023-10-05 09:03
Yeah I picked that up after I sent the mail and retried it

Get Outlook for iOS<https://aka.ms/o0ukef>

James Hendry
General Manager  Commercial
D 03 8696 9304M 0400 660 006
E ***@***.***
CONFIDENTIALITY NOTICE:  The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.
________________________________

**Comment by MicheleCardamone** [comment] 2023-10-05 14:32
> When it finishes building please try out [this one](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6414580353)

HI! @QuantumEntangledAndy 
with this build i have this error
![Screenshot 2023-10-05 162836](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/b1015868-e858-43e0-b061-e3f4604a82ff)

**Comment by QuantumEntangledAndy** [comment] 2023-10-05 23:52
This is very odd because a no reactor is a async Tokio error. But line 1085 is not any sort of async code in fact line 1085 and column 33 dosent exist in that build. So please send me the version string that's near the top of the log so I can check which has commit this was built with.

**Comment by MicheleCardamone** [comment] 2023-10-06 07:33
> This is very odd because a no reactor is a async Tokio error. But line 1085 is not any sort of async code in fact line 1085 and column 33 dosent exist in that build. So please send me the version string that's near the top of the log so I can check which has commit this was built with. 

![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/3d947db2-bcd9-454f-a7dd-157806dcade8)

**Comment by QuantumEntangledAndy** [comment] 2023-10-06 08:09
Do you by any chance get the H265 video stream?

**Comment by QuantumEntangledAndy** [comment] 2023-10-06 08:16
Might have found it, please try [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6429184116)

**Comment by QuantumEntangledAndy** [comment] 2023-10-06 08:17
This build has an experimental pausing of the IFrame in it that I was working on. Might need tweaking as I think it is making video frames come in waves

**Comment by MicheleCardamone** [comment] 2023-10-06 15:56
> ```batchfile
> > neolink.log 2>&1
> ```

Hi @QuantumEntangledAndy 
tested. The Tokyo error seems to no longer exist but it doesn't work anyway: main and sub totally with fps out of limit. 
![Screenshot 2023-10-06 175136](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/a3c3647b-3d85-4651-97b2-4015b76f46c5)

**Comment by MicheleCardamone** [comment] 2023-10-08 11:39
Hi!
@QuantumEntangledAndy any update about this problem?

**Comment by QuantumEntangledAndy** [comment] 2023-10-08 12:29
There are a few different problems in this thread and it is getting difficult to track. Since the original memory one seems solved perhaps we should close this and open a new one. You can however test [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6447209602) which I have been working to make the stream simpiler and more reliable in vlc

**Comment by QuantumEntangledAndy** [comment] 2023-10-08 13:37
Well when you have time please check this latest build and then open a new issue with anything you find in it. That will help me know what still needs to be addresed. For now closing as the memory seems to be addressed

**Closed by QuantumEntangledAndy** 2023-10-08 13:37 UTC
Labels: bug

**Comment by QuantumEntangledAndy** [comment] 2023-10-08 13:39
[This build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6447986861) please, just squashed one more bug raised in another issue
