### ISSUE TITLE
Reaching limit of channel | Remaining: 0 of 100 message space for 4 (ID: 3)

### ISSUE THREAD

**Issue by apedance** [QuantumEntangledAndy/neolink#143] opened 2023-08-29 00:14 UTC
**Describe the bug**
neolink camera stops working after x amount of time with error:

[2023-08-28T22:44:50Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel [2023-08-28T22:44:50Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)

hard reset of neolink is needed to get the camera working again.

**Comment by QuantumEntangledAndy** [comment] 2023-08-29 00:37
Duplicate of  #117 I think

**Comment by apedance** [comment] 2023-08-29 01:05
Indeed. But not for the media part. Not having that issue.
Just the reaching limit of channel.
Any idea how to solve?

**Comment by QuantumEntangledAndy** [comment] 2023-08-29 01:09
Right but the (ID: 3) is a media message so it should be the same thing

**Comment by QuantumEntangledAndy** [comment] 2023-08-29 01:11
As far as I can tell it is because the media part of the channel is not pulling the messages off of the stream fast enough. The whole part of the media code is quite complex so I am working on a refractor to hopefully remove this complexity and make it easier to pull messages off of the queue

**Comment by jamesahendry** [comment] 2023-09-08 21:52
I have 6 cams on Neolink.  I've tried Windows environments, Linux. The consistent theme I've come to is that they work much better if you only have 1 cam per instance.  I get far less drop-outs on Frigate and the Frigate logs are clear.  I've now separated out a Debian LXC on proxmox for each cam. Once you have the first one established, just copy it, edit TOML and away you go.  They've only been up a day on their LXC, but they seem to behave very differently in terms of their resource consumption.

**Comment by QuantumEntangledAndy** [comment] 2023-09-19 05:34
This should now be fixed on latest, can anyone confirm?

**Comment by MicheleCardamone** [comment] 2023-09-20 04:50
Hi. Same error for me, with 0.6.0
After few hours of correct functioning i have this error.

it seems to be very similar to the previous timed out error, with the difference that some cams present the rtsp 503 error ![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/9ffa1fc5-7e62-4d1f-8c0e-2adb4be0a24f)

**Comment by QuantumEntangledAndy** [comment] 2023-09-20 05:42
So this is quite odd. This warning message occurs when 100 messages are in the queue. Meaning we got 100 messages from the camera but the app has not processed them.

The odd thing is that there is no real processing going on. The app pulls a message converts it to bcmedia then instantly puts it in a broadcast stream with no waiting around.

The only part I can think of that might be causing this is if the conversion from bc->bcmedia is somehow stalling the process. So in that regards I made this [build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/624446921) that uses a different (and hopefully less error prone) way of filtering and converting bc packets into bcmedia packets. Could you test it?

**Comment by MicheleCardamone** [comment] 2023-09-20 05:56
> So this is quite odd. This warning message occurs when 100 messages are in the queue. Meaning we got 100 messages from the camera but the app has not processed them.
> 
> 
> 
> The odd thing is that there is no real processing going on. The app pulls a message converts it to bcmedia then instantly puts it in a broadcast stream with no waiting around.
> 
> 
> 
> The only part I can think of that might be causing this is if the conversion from bc->bcmedia is somehow stalling the process. So in that regards I made this [build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/624446921) that uses a different (and hopefully less error prone) way of filtering and converting bc packets into bcmedia packets. Could you test it?

Sure, as soon as I have time today I will do it and I'll update you!

**Comment by MicheleCardamone** [comment] 2023-09-20 12:07
> So this is quite odd. This warning message occurs when 100 messages are in the queue. Meaning we got 100 messages from the camera but the app has not processed them.
> 
> The odd thing is that there is no real processing going on. The app pulls a message converts it to bcmedia then instantly puts it in a broadcast stream with no waiting around.
> 
> The only part I can think of that might be causing this is if the conversion from bc->bcmedia is somehow stalling the process. So in that regards I made this [build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/624446921) that uses a different (and hopefully less error prone) way of filtering and converting bc packets into bcmedia packets. Could you test it?

I can't download it, it says it doesn't exist

**Comment by QuantumEntangledAndy** [comment] 2023-09-20 12:29
Seems I missed the `0` at the end of the link. Here is the [right one](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6244469210)

**Comment by MicheleCardamone** [comment] 2023-09-20 12:40
> Seems I missed the `0` at the end of the link. Here is the [right one](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6244469210)

Tested, all cam seems to work but just started it gives errors in gstream
![Screenshot 2023-09-20 143729](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/54c7cacd-28c9-43e7-8745-f2ed45c12ebb)

**Comment by QuantumEntangledAndy** [comment] 2023-09-20 13:55
Ah that error, it was part of my experiment with buffering in gstreamer, it is already fixed in latest

**Comment by MicheleCardamone** [comment] 2023-09-20 16:17
> I think you can use [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6244649051) to confirm its fixed

This build has been testing and has not given any errors so far. However, there seems to be this effect (I attach photos) in the recordings, which seems like saturation
![Screenshot 2023-09-20 181601](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/264e229c-e1b2-407a-9468-046f124e8d74)

**Comment by QuantumEntangledAndy** [comment] 2023-09-21 01:27
This isn't saturation it's an incomplete video frame. These usually happen across reconnect boundaries or at the start of a stream

**Comment by QuantumEntangledAndy** [comment] 2023-09-21 02:09
What I can do is make neolink wait for a key frame before sending anything onwards between resets but this will mean that some frames will be skipped while waiting for a key frame

**Comment by QuantumEntangledAndy** [comment] 2023-09-21 02:39
So build with the filtered for first keyframe is [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6256520629) at this point though perhaps we should test if these lots of reconnects are happening because of network congestion. Have you tried things like reducing the bitrate and fps on the cameras?

**Comment by MicheleCardamone** [comment] 2023-09-21 05:34
> So build with the filtered for first keyframe is here at this point though perhaps we should test if these lots of reconnects are happening because of network congestion. Have you tried things like reducing the bitrate and fps on the cameras?

Good morning. the latest build I was testing this morning seems to have failed. I didn't find any errors, the neolink process simply closed. a bit strange. However the bitrate is 4096 on the main stream with 20 fps

**Comment by QuantumEntangledAndy** [comment] 2023-09-21 06:55
I am not observing this close without errors issue that you have. Also perhaps we should do this on another thread since it seems to not be related to this issue

**Comment by MicheleCardamone** [comment] 2023-09-21 07:10
> I am not observing this close without errors issue that you have. Also perhaps we should do this on another thread since it seems to not be related to this issue

Ok, I will open another thread

**Comment by MicheleCardamone** [comment] 2023-09-21 15:31
![Screenshot 2023-09-21 171917](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/9bf0ec63-dc11-4ab9-a407-37184f20b326)
Hi! same problem with the latest build you posted too

**Comment by QuantumEntangledAndy** [comment] 2023-09-22 04:55
That's a shame how long does it take to get to this state? Do you still get to it even with 1 camera? I ask because if I want to trace this I might need to make a wireshark dump but I only have 2 cameras and wireshark won't play nicely over hours of connectiity

**Comment by QuantumEntangledAndy** [comment] 2023-09-22 04:57
Does this error correct itself? I have a watch dog that looks for 3s of no video and then restarts it. This should look like 3s of no video for the watch dog which should mean that the stream will restart and you will get 100 message space again

**Comment by QuantumEntangledAndy** [comment] 2023-09-22 05:01
If you can turn on debug log you can see when the watchdog kicks the stream.  Set the env var`RUST_LOG` to `debug`

**Comment by MicheleCardamone** [comment] 2023-09-22 05:58
> That's a shame how long does it take to get to this state? Do you still get to it even with 1 camera? I ask because if I want to replicate and trace this issue I might need to make a wireshark dump but I only have 2 cameras and wireshark won't play nicely over hours of connectiity

I didn't count it exactly, but the time is certainly more than 6 hours of correct functioning. There seems to have been a slightly different error, still relating to this typology.![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/d52ec936-a941-481b-9627-a2d9f4663d81)

However, no, it doesn't seem to resolve itself. I always have to restart neolink.

could I try creating 2 separate instances with different ports, one with 8 cams and one with just one cam, to see what happens?

**Comment by QuantumEntangledAndy** [comment] 2023-09-22 08:35
It look like you ran out of RAM could you check that? Maybe show a graph of ram over time

**Comment by MicheleCardamone** [comment] 2023-09-24 11:08
> It look like you ran out of RAM could you check that? Maybe show a graph of ram over time 

I haven't had a chance to check these days. I think I'll be able to let you know tomorrow. Has 0.6.1 fixed any of my problems from what you know? THANKS! 
Mc @QuantumEntangledAndy

**Comment by QuantumEntangledAndy** [comment] 2023-09-24 11:42
0.6.1 is mostly an mqtt fix but it does include the other fixes we did with regards to BI start ups. You can see a summary of what's included in the release page

**Comment by MicheleCardamone** [comment] 2023-09-26 16:17
> It look like you ran out of RAM could you check that? Maybe show a graph of ram over time

![Screenshot 2023-09-26 181235](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/85a02b38-9eb1-4860-b525-39cf8991f80b)
testing with 0.6.2 Everything seems to work fine for the first 9 hours. However, I notice that the neolink task manager seems to consume more and more RAM, to restore it just restart the process. It is currently consuming around 5GB and increasing more and more

**Comment by QuantumEntangledAndy** [comment] 2023-09-26 23:15
Yes I got rid of the large mem growth in 0.6.2 but there is a little bit left. I have some more fixes in the work that takes it down to zero at least for my macOS and Linux (can't test the windows) hopefully that will fix it.

**Comment by jamesahendry** [comment] 2023-09-26 23:28
Can I get you to check the mem growth in the scenario where you access both the SubSteam and Mainsteam?  I use this in Frigate BTW.  I have some of my cams that detect on the Mainsteam only due to the field of view and I've cut the cam up into different zones within Frigate.  Other cams I use substeam to detect and mainstream to record.  I am seeing vastly different memory growth when I am accessing both the sub and mainstreams compared to the mainstream only (which is 4K).  The 4K only memory steam is very static - very consistent on 0.6.2.  The sub/main combination is consistently growing and I run reboot on the Bullseye container when it gets close to 1GB.  1 cam per container.  Here's the difference yesterday.  I have 3 cams running mainsteam only and 3 cams running sub/main so the consistency is absolute depending on the scenario.  There's also an auto reboot at circa 4AM due to the memory issues.  I could isolcate this by spinning up a new LXC and splitting the sub/main and test if you want?


![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/9459dcbd-ec01-479a-8ffe-ee4058758bc0)

![image](https://github.com/QuantumEntangledAndy/neolink/assets/67103059/be86132a-f320-4c15-b0e9-a1bcb4885d19)

**Comment by MicheleCardamone** [comment] 2023-09-27 12:20
> Yes I got rid of the large mem growth in 0.6.2 but there is a little bit left. I have some more fixes in the work that takes it down to zero at least for my macOS and Linux (can't test the windows) hopefully that will fix it. 

unfortunately the previous problem seems to have recurred again with 0.6.2 master.![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/e1d20f42-0a2f-48bc-9169-22681e97414a) ![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/b13e65c1-a3ea-43b4-b17e-c9f4af2463ca)

**Comment by kniteli** [comment] 2023-10-31 21:40
I think this might be partially on the hardware side too. Neolink drops the camera when this starts happening, but I even see a lot frame dropping and general instability on the stream through reolink too, only on the one device so far. E1 if it helps.

**Comment by alenzurfluh** [comment] 2024-01-10 19:44
Hi, are you guys still facing this issue?

I'm using a  Reolink Lumus and seeing simliliar issues here:

`[2024-01-09T23:35:52Z WARN  fcm_push_listener::listener] Connection failed. Retrying.
[2024-01-09T23:39:32Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2024-01-09T23:39:32Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 100 of 100 message space for 5 (ID: 3)
[2024-01-09T23:39:39Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2024-01-09T23:39:39Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 69 of 100 message space for 5 (ID: 3)
Killed`

**Comment by QuantumEntangledAndy** [comment] 2024-04-26 04:31
Haven't had any reports on this error in quite some time, so I will be closing it. Let me know if this is still happening on latest

**Closed by QuantumEntangledAndy** 2024-04-26 04:31 UTC
Labels: duplicate
